import React from 'react';
import './LivingSection.css';

const livingData = [
  {
    title: 'Style',
    articles: [
      {
        img: 'https://tse4.mm.bing.net/th/id/OIP.Vf1JUm1lIX_h-r545o1bPQHaFN?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        title: 'Remember When Things Were Better in the ’90s? A.I. Does Too.',
        description: 'Marc Jacobs and Sofia Coppola’s Very Stylish Friendship',
        extra: '10 Unforgettable Looks at the MTV Video Music Awards',
        label: 'GENERATED BY A.I.',
        featured: true
      },
      {
        img: 'https://tse4.mm.bing.net/th/id/OIP.Vf1JUm1lIX_h-r545o1bPQHaFN?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        title: 'Second Style Article',
        description: 'A brief description of the second style article.',
        featured: false
      }
    ]
  },
  {
    title: 'Food',
    articles: [
      {
        img: 'https://tse4.mm.bing.net/th/id/OIP.Vf1JUm1lIX_h-r545o1bPQHaFN?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        title: 'The Restaurant List 2025',
        description: 'What’s New in School Lunchrooms: Less Sugar, More From Scratch',
        extra: 'Our Staff’s Restaurants of the Year, Plus Takes and Trends From 2025',
        featured: false
      }
    ]
  },
  {
    title: 'Travel',
    articles: [
      {
        img: 'https://tse4.mm.bing.net/th/id/OIP.Vf1JUm1lIX_h-r545o1bPQHaFN?r=0&rs=1&pid=ImgDetMain&o=7&rm=3',
        title: 'A Sweaty, Salty Trip Along Ireland’s Wild Atlantic Way',
        description: "What Travelers Need to Know About the ‘Block Everything’ Strike in France",
        featured: true
      }
    ]
  }
];

export default function LivingSection() {
  return (
    <section className="living-section">
      {livingData.map((category, i) => (
        <div key={i} className="category">
          <h3>{category.title}</h3>
          <div className="articles">
            {category.articles.map((article, j) => (
              <article key={j} className={`article ${article.featured ? 'featured' : ''}`}>
                <img src={article.img} alt={article.title} />
                <div className="text-content">
                  <h4>{article.title}</h4>
                  <p>{article.description}</p>
                  {article.extra && <small>{article.extra}</small>}
                  {article.label && <span className="label">{article.label}</span>}
                </div>
              </article>
            ))}
          </div>
        </div>
      ))}
    </section>
  );
}
